# Generated by Django 4.2.4 on 2023-09-19 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_clientdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clientdata',
        ),
    ]
