# Generated by Django 4.2.4 on 2023-09-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_delete_clientdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('dob', models.DateField(blank=True, default=None, null=True)),
                ('aadhar', models.CharField(max_length=15)),
                ('street', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
            ],
        ),
    ]
