# Generated by Django 4.2.4 on 2023-09-19 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_clientdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('dob', models.DateField(blank=True, default=None, null=True)),
                ('aadhar', models.CharField(max_length=15)),
                ('street', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
        migrations.DeleteModel(
            name='clientdata',
        ),
    ]
