# Generated by Django 4.2.4 on 2023-09-19 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_clientinfo_delete_clientdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientdocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdfdata', models.FileField(blank=True, null=True, upload_to='documents')),
                ('qrdata', models.ImageField(blank=True, null=True, upload_to='qrcode')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.clientinfo')),
            ],
        ),
    ]
